using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using StringCompareSettings;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DeadBodyCleanupNPCAttacher
{
    public class Program
    {
        static Lazy<Settings> _patchSettings = null!;
        public static Settings Settings => _patchSettings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _patchSettings)
                // Atualizado para SkyrimSE: obrigatório para suportar ESLs na Anniversary Edition e passar dos 255 plugins.
                .SetTypicalOpen(GameRelease.SkyrimSE, "DeadBodyCleanupNPCpatch.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            string unofficialPatchName = Settings.UnofficialPatchName;
            
            // O método FromNameAndExtension foi removido da API. 
            ModKey unofficialPatchModKey = ModKey.FromFileName(unofficialPatchName);

            if (!state.LoadOrder.ContainsKey(unofficialPatchModKey))
            {
                Console.WriteLine($"{unofficialPatchName} not found. Finish.");
                return;
            }

            int forwarded = 0;
            if (!state.LoadOrder.TryGetValue(unofficialPatchModKey, out IModListing<ISkyrimModGetter>? unofficialPatchModGetter) || unofficialPatchModGetter?.Mod == null)
            {
                Console.WriteLine($"{unofficialPatchName} not found. Finish.");
                return;
            }

            foreach (var unPatchNPCGetter in unofficialPatchModGetter.Mod.Npcs)
            {
                if (unPatchNPCGetter == null) continue;
                var theScriptEntrieGetter = unPatchNPCGetter.VirtualMachineAdapter?.Scripts.FirstOrDefault(s => string.Equals(s.Name, "wideadbodycleanupscript", StringComparison.InvariantCultureIgnoreCase));
                if (theScriptEntrieGetter == null) continue;

                var contexts = state.LinkCache.ResolveAllContexts<INpc, INpcGetter>(unPatchNPCGetter.FormKey).ToList();
                if (!contexts.Any()) continue;
                
                var lastNPCEdit = contexts.First(); 
                if (lastNPCEdit.ModKey == unofficialPatchModKey) continue; 
                if (lastNPCEdit.Record.VirtualMachineAdapter != null && lastNPCEdit.Record.VirtualMachineAdapter.Scripts.Any(s => string.Equals(s.Name, "wideadbodycleanupscript", StringComparison.InvariantCultureIgnoreCase))) continue; 

                forwarded++;
                var patchedNPC = state.PatchMod.Npcs.GetOrAddAsOverride(lastNPCEdit.Record);
                Console.WriteLine($"Forward script for npc '{patchedNPC.FormKey.ID:X6}'({patchedNPC.EditorID}:[{patchedNPC.Name}])");
                
                patchedNPC.VirtualMachineAdapter ??= new VirtualMachineAdapter();
                patchedNPC.VirtualMachineAdapter.Scripts.Add(theScriptEntrieGetter.DeepCopy());
            }
            Console.WriteLine($"Forwarded script for {forwarded} npcs");

            if (Settings.OnlyScriptForward)
            {
                Console.WriteLine("Selected only script forward, skip add...");
                return;
            }

            var deadBodyCleanupScript = new ScriptEntry
            {
                Name = "WIDeadBodyCleanupScript",
                Flags = ScriptEntry.Flag.Local
            };

            // Parse em string não é mais suportado. Uso do construtor direto em hexadecimal.
            var skyrimModKey = ModKey.FromFileName("Skyrim.esm");

            var deathContainerScriptProperty = new ScriptObjectProperty
            {
                Name = "DeathContainer",
                Flags = ScriptProperty.Flag.Edited,
                Object = new FormLink<IContainerGetter>(new FormKey(skyrimModKey, 0x0172B6))
            };
            deadBodyCleanupScript.Properties.Add(deathContainerScriptProperty);

            var wiScriptProperty = new ScriptObjectProperty
            {
                Name = "WI",
                Flags = ScriptProperty.Flag.Edited,
                Object = new FormLink<IQuestGetter>(new FormKey(skyrimModKey, 0x035d64))
            };
            deadBodyCleanupScript.Properties.Add(wiScriptProperty);

            var playerFormkey = new FormKey(skyrimModKey, 0x000007);
            bool playerFound = false;
            
            StringCompareHelpers.IsUsingSkipList = Settings.SkipList.Count > 0 && Settings.SkipList.Any(s => !string.IsNullOrWhiteSpace(s.StringSetting?.Name));
            var skipList = Settings.SkipList;

            int added = 0;
            foreach (var npcGetter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                if (!playerFound && npcGetter.FormKey == playerFormkey)
                {
                    playerFound = true;
                    continue;
                }
                
                if (!npcGetter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Unique)) continue; 
                if (npcGetter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.IsCharGenFacePreset)) continue; 
                if (npcGetter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Summonable)) continue; 
                if (npcGetter.Template != null && !npcGetter.Template.IsNull && npcGetter.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Script)) continue; 
                if (npcGetter.VirtualMachineAdapter != null && npcGetter.VirtualMachineAdapter.Scripts.Any(s => string.Equals(s.Name, "wideadbodycleanupscript", StringComparison.InvariantCultureIgnoreCase))) continue; 
                
                if (npcGetter.EditorID?.IsInSkipList(skipList) == true) continue;

                added++;
                var npc = state.PatchMod.Npcs.GetOrAddAsOverride(npcGetter);
                Console.WriteLine($"Add script for npc '{npcGetter.FormKey.ID:X6}'({npcGetter.EditorID}:[{npcGetter.Name}])");

                npc.VirtualMachineAdapter ??= new VirtualMachineAdapter();
                // O Mutagen rejeitará a injeção do script se não for uma cópia isolada na memória (DeepCopy)
                npc.VirtualMachineAdapter.Scripts.Add(deadBodyCleanupScript.DeepCopy()); 
            }

            Console.WriteLine($"Added script for {added} npcs");
        }
    }
}